### ISSUE TITLE
How can i use it?

### ISSUE THREAD

**Issue by itlixiaolong** [chrisguttandin/element-shot#106]

**Comment by chrisguttandin** [comment]
Hi @itlixiaolong,

sorry for not providing meaningful documentation so far. I'm using this package to take screenshots in visual regression tests of Angular projects.

Please take a look at the tests over here for an example: https://github.com/chrisguttandin/audio-developer-conference-2019/blob/master/test/regression/slides.ts

Unfortunately the Angular team is not including any e2e tests anymore when creating a new project with the CLI and I guess Protractor itself will be deprecated sooner or later. Therefore this package is about to be deprecated, too.

I hope this helps. Please let me know if you run into any issues.
